import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import RankSelector from "../components/RankSelector";

const Home: NextPage = () => {

  const [startRank, setStartRank] = useState(-1);
  const [endRank, setEndRank] = useState(-1);

  return (
    <>
      <Head>
        <title>Boosting</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-3xl md:text-5xl font-extrabold leading-normal text-gray-400 md:text-[5rem]">
          Valorant <span className="text-yellow-500">Boosting</span>
        </h1>
        <br/>
        <div className="sm:flex">
          <div>
            <RankSelector updateValue={(value:number)=>{ 
              setStartRank(value);
            }} />
          </div>
          <div>
            <RankSelector updateValue={(value:number)=>{ 
              setEndRank(value);
            }} />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;